[package]
name = "use_derive_macro"
version = "0.1.0"
authors = ["DaMianYang <hugo.dupuyroudel@outlook.com>"]
edition = "2018"

[dependencies]
derive_macro = { path = "../derive_macro" }
derive_macro_derive = { path = "../derive_macro/derive_macro_derive" }
